const fs = require('fs');
const crypto = require('crypto');
const password = 'Always/834875';
const iterations = 100000;
const keylen = 32;
const digest = 'sha256';
const salt = crypto.randomBytes(16).toString('base64');
const derived = crypto.pbkdf2Sync(password, Buffer.from(salt, 'base64'), iterations, keylen, digest);
const out = derived.toString('base64') + "\n" + salt + "\n" + iterations + "\n" + digest + "\n";
fs.writeFileSync('./pbkdf2.txt', out);
console.log('WROTE ./pbkdf2.txt');
