CREATE TABLE skate_cards (
  id TEXT PRIMARY KEY,
  skater_id TEXT NOT NULL,

  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,               -- generated by branding tool
  rarity TEXT,                  -- common | rare | legendary | 1-of-1
  edition_size INTEGER,         -- total number minted
  price_cents INTEGER,          -- optional price
  created_at TEXT NOT NULL,

  FOREIGN KEY (skater_id) REFERENCES skater_profiles(id)
);
